version: "3.7"
services: 
    proxy_web:
        build: .
        ports: 
            - "5050:5050"
        depends_on: 
            - redis
        environment: 
            - PROXYPOOL_DEV=1
        volumes: 
            - "./production/config:/app/production/config"
    redis:
        image: redis
        volumes: 
            - "./production/data:/data"
        command: redis-server --appendonly yes